### PR TITLE
Add Windows support - Fix tests, enable CI, and release Windows binaries

### LINKED ISSUE #778: Release builds for Windows
I'd like to use crane in one of my open source projects, [AdaptJS](https://github.com/unboundedsystems/adapt), which deploys and manages containers and other app infrastructure. But we'd like to ensure Adapt can continue to run on Windows platforms. Would it be possible to build and release official Windows binaries for crane?

I have built crane from source on Windows 10 and so far, I haven't run into any issues. But our users would be downloading the binaries directly onto their own systems and so we'd prefer to have them do that from the official releases.

If you'd like, I'm willing to look into creating a pull request to enable Windows builds.

### PR DESCRIPTION
**Pull request by mterrel**
Fixes #778 

With these changes, all tests pass running on a Windows system with Docker in Linux container mode.
One test file cannot run if Docker is in Windows container mode because crane can only pull Linux containers.

I'm not normally a Go developer, so let me know if I need to make any changes to how I've done anything here.

Please take a hard look at the "unclosed ReadClosers" fix, as that one is the most involved and has the most potential for me to have done something incorrectly.

### CODE REVIEW

**Comment by mterrel** [comment]
@googlebot I signed it!

**Comment by mterrel** [comment]
@jonjohnsonjr Are there any questions I can answer or anything you need from me on this PR?

**Comment by jonjohnsonjr** [comment]
> any questions I can answer or anything you need from me on this PR?

Not yet! I'm currently in the process of moving, so my life is a bit hectic at the moment. Hopefully I'll be able to give this a proper review by the end of the week (no promises!).

Apologies for the delay, I really appreciate your contribution here.

**Comment by mterrel** [comment]
> > any questions I can answer or anything you need from me on this PR?
> 
> Not yet! I'm currently in the process of moving, so my life is a bit hectic at the moment. Hopefully I'll be able to give this a proper review by the end of the week (no promises!).
> 
> Apologies for the delay, I really appreciate your contribution here.

No worries. I know how all-consuming moving can be. Hope all goes well!

File: pkg/v1/mutate/mutate.go [hunk 1]
```diff
@@ -175,52 +175,60 @@ func extract(img v1.Image, w io.Writer) error {
...
-		tarReader := tar.NewReader(layerReader)
-		for {
-			header, err := tarReader.Next()
-			if err == io.EOF {
-				break
-			}
-			if err != nil {
-				return fmt.Errorf("reading tar: %v", err)
-			}
+		readLayer := func() error {
```
Comment (jonjohnsonjr) [inline pkg/v1/mutate/mutate.go:178]: Do you need to introduce a new function here? I think we could just defer the `layerReader.Close()` and let that happen whenever we return from `extract`.

**Review by jonjohnsonjr — COMMENTED** [review]
> One test file cannot run if Docker is in Windows container mode because crane can only pull Linux containers.

Let's try that again when https://github.com/google/go-containerregistry/pull/742 lands.

File: pkg/v1/mutate/mutate.go (hunk 1 above)
Comment (mterrel) [reply pkg/v1/mutate/mutate.go:178]: I wasn't sure of the exact semantics of how `defer layerReader.Close()` would work in this loop, which is what led to my extra caution of ensuring each `layerReader` got closed before the end of the loop iteration.

So just to confirm: if I do `defer layerReader.Close()` in the loop, `layerReader` will get captured immediately, meaning every `layerReader` created in the loop will get closed upon return from `extract`?

Comment (jonjohnsonjr) [reply pkg/v1/mutate/mutate.go:178]: > layerReader will get captured immediately, meaning every layerReader created in the loop will get closed upon return from extract

Yeah that's my understanding, it should be fine, but I'm going to appeal to someone with more golang trivia knowledge cc @ImJasonH

Comment (mterrel) [reply pkg/v1/mutate/mutate.go:178]: One more question: Is there a stack/scalability problem if there are a large number of layers?

Comment (jonjohnsonjr) [reply pkg/v1/mutate/mutate.go:178]: I think that's technically possible, but in practice images won't have more than ~128 layers due to technical limitations of container runtimes. I could see this being a problem if someone is abusing container image formats for other purposes, but unless we actually run into that, I'd prefer the readability of one less level of indentation.

Comment (mterrel) [reply pkg/v1/mutate/mutate.go]: Fixed.

**Comment by mterrel** [comment]
@jonjohnsonjr Ok, I made the requested changes and rebased to master.

**Review by jonjohnsonjr — APPROVED** [review]
Thanks so much for this!

**Comment by mterrel** [comment]
@jonjohnsonjr Would it be possible to publish a release that contains these changes?

**Comment by jonjohnsonjr** [comment]
Certainly! I'm juggling a few things but I want to test https://github.com/google/go-containerregistry/pull/851 against travis and get it merged before I cut a new release. Hopefully I can get to it by the end of today (and if you see anything glaringly wrong about that PR, please let me know).

**Comment by mterrel** [comment]
@jonjohnsonjr Awesome! Thanks for the new release! 😃
