### PR TITLE
gcrane: use a task queue when copying images

### LINKED ISSUE #424: Gcrane: unrecognized HTTP status: 429 Too Many Requests
I'm trying to migrate a large number of data (over 38000) to a new GCR. Gcrane fails with a following error:
"failed to copy image: reading image "XXXXX": unrecognized HTTP status: 429 Too Many Requests" that means a Cloud Storage JSON API usage limit was exceeded.

Command executed: 
gcrane cp -r [old_GCR] [new_GCR]

How can it be fixed?

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
This will naturally throttle us based on our concurrency.

Also adds retry with backoff in case we hit 429s, 5xxs or temporary
errors with GCR.

Fixes #424

### CODE REVIEW

File: pkg/gcrane/copy.go [hunk 1]
```diff
@@ -33,6 +37,27 @@ import (
...
 
+// These numbers are based on GCR's posted quotas:
+// https://cloud.google.com/container-registry/quotas
+// -  30k requests per 10 minutes.
+// - 500k requests per 24 hours.
+//
+// On error, we will wait for:
+// - 6 seconds (in case of very short term 429s from GCS), then
+// - 1 minute (in case of temporary network issues), then
+// - 10 minutes (to get around GCR 10 minute quotas), then fail.
```
Comment (ImJasonH) [inline pkg/gcrane/copy.go]: What's the `Cap: 1 * time.Hour` for?

Comment (jonjohnsonjr) [reply pkg/gcrane/copy.go]: Basically to make sure I don't have an off-by-one error in my understanding of ExponentialBackoff. We don't really want to sit around for any longer than an hour, ever.
